<!-- Galeria de imagenes proteccion y servicio start -->
<section class="galeria parent-container slider-g mb-5">

  <div>
    <a class="transition popup-img" title="Muebles de Exterior" href="img/muebles-gr-a.jpg">
      <img class="img-fluid" src="img/muebles-ch-a.jpg" alt="galeria a chica">
    </a>
  </div>

  <div>
    <a class="transition popup-img" title="Muebles de Exterior" href="img/muebles-gr-b.jpg">
      <img class="img-fluid" src="img/muebles-ch-b.jpg" alt="galeria a chica">
    </a>
  </div>

  <div>
    <a class="transition popup-img" title="Muebles de Exterior" href="img/muebles-gr-c.jpg">
      <img class="img-fluid" src="img/muebles-ch-c.jpg" alt="galeria a chica">
    </a>
  </div>

  <div>
    <a class="transition popup-img" title="Muebles de Exterior" href="img/muebles-gr-d.jpg">
      <img class="img-fluid" src="img/muebles-ch-d.jpg" alt="galeria a chica">
    </a>
  </div>

  <div>
    <a class="transition popup-img" title="Muebles de Exterior" href="img/muebles-gr-e.jpg">
      <img class="img-fluid" src="img/muebles-ch-e.jpg" alt="galeria a chica">
    </a>
  </div>

  <div>
    <a class="transition popup-img" title="Muebles de Exterior" href="img/muebles-gr-f.jpg">
      <img class="img-fluid" src="img/muebles-ch-f.jpg" alt="galeria a chica">
    </a>
  </div>

</section>
<!-- Galeria de imagenes proteccion y servicio end -->