<section class="full-width-section pv-40 light-gray-bg border-clear">
	<div class="full-text-container text-right left light-gray-bg border-clear">
		<br class="hidden-sm hidden-xs">

		<div class="feature-box-2 right margin-clear">
			<span class="icon without-bg"><img src="images/deck-contour/sistema-oculto/tilde.gif" alt="tilde"></span>
			<div class="body">
				<h4>Sistema de fijación oculta.</h4>
				<p>
					El sistema de fijación invisible Trex Hideaway&reg;
					es una opción de tablas con borde acanalado
					para un espaciado perfectamente uniforme
					y sin tornillos visibles en la parte superior.
				</p>
				<div class="separator-3 visible-lg"></div>
			</div>
		</div>

	</div>
	<div class="clearfix">
		<img class="object-non-visible animated object-visible slideInDown" data-animation-effect="slideInDown" data-effect-delay="100"
		src="images/deck-contour/sistema-oculto/01-Sistema-oculto-contour-deck-ecologico-trex.png" alt="sistema oculto">
	</div>
</section>