<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

  <div class="container">
    <div class="row">
        <h3 class="text-center">COLORES DISPONIBLES</h3> 
        
      <!-- main start -->
      <!-- ================ -->
      <div class="main col-md-12">
        <div class="isotope-container row grid-space-10">

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-enhance/arena-tostado.jpg" alt="color gris castor">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-enhance-plastico-arena-tostado.php">Color Arena Tostado</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-enhance-plastico-arena-tostado.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-enhance/caoba.jpg" alt="Color Caoba">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-enhance-plastico-caoba.php">Color Caoba</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-enhance-plastico-caoba.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-enhance/gris-muelle.jpg" alt="Color Gris Muelle">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-enhance-plastico-gris-muelle.php">Color Gris Muelle</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-enhance-plastico-gris-muelle.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-enhance/gris-piedra.jpg" alt="Color Gris Piedra">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-enhance-plastico-gris-piedra.php">Color Gris Piedra</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-enhance-plastico-gris-piedra.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-enhance/gris-plomo.jpg" alt="Color Gris Plomo">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-enhance-plastico-gris-plomo.php">Color Gris Plomo</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-enhance-plastico-gris-plomo.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-enhance/nogal.jpg" alt="Color Nogal">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-enhance-plastico-nogal.php">Color Nogal</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-enhance-plastico-nogal.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
      <!-- main end -->

    </div>
  </div>
</section>
<!-- main-container end -->