<section class="main-container">

  <div class="container">
    <div class="row">
        <h3 class="text-center">COLORES DISPONIBLES</h3> 
        
      <!-- main start -->
      <!-- ================ -->
      <div class="main col-md-12">
        <div class="isotope-container row grid-space-10">

          <!-- Color -->
          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-co-extruded/corte-antique.jpg" alt="deck co-extruded antique">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-co-extruded-antique.php">Co-Extruded - Antique</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-co-extruded-antique.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Color end -->

          <!-- Color -->
          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-co-extruded/corte-silver.jpg" alt="deck co-extruded silver">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-co-extruded-silver.php">Co-Extruded - Silver</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-co-extruded-silver.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Color end -->

          <!-- Color -->
          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-co-extruded/corte-teka.jpg" alt="deck co-extruded teka">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-co-extruded-teka.php">Co-Extruded - Teka</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-co-extruded-teka.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Color end -->

        </div>
      </div>
      <!-- main end -->

    </div>
  </div>
</section>