<section class="full-width-section pv-40 border-clear">
	<div class="full-text-container text-right left border-clear">
		<br class="hidden-sm hidden-xs">

		<div class="feature-box-2 right margin-clear">
			<div class="body">
				<h4 class="tipo_2em">COMPOSICIÓN Y TEXTURA<br> CON VETAS SIMIL MADERA</h4>
				<div class="separator-3 visible-lg"></div>
			</div>
		</div>

	</div>
	<div class="clearfix">
		<img class="object-non-visible animated object-visible slideInDown" data-animation-effect="slideInDown" data-effect-delay="100"
		src="images/deck-contour/liston.jpg" alt="liston">
	</div>
</section>
