<section class="light-gray-bg pv-30 clearfix">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<h3 class="text-center">¿Por qué elegir nuestros <strong>DECKS ECOLÓGICOS?</strong></h3>
				<div class="separator"></div>
				<p class="large text-center">Diseñados especificamente para que se vean siempre como nuevos, incluso décadas después de su instalación.</p>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
					<span class="icon large circle">
						<img width="165" height="165" class="img-circle" alt="deck sin mantenimiento" src="images/deck-trascend/mantencion.gif">
					</span>
					<h3 class="bold">MANTENCIÓN</h3>
					<div class="separator clearfix"></div>
					<p class="text-muted">LAVADO CON AGUA Y JABÓN O LAVADORA DE PRESIÓN.</p>
				</div>
			</div><div class="col-md-4 col-sm-6">
				<div class="ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
					<span class="icon large circle">
						<img width="165" height="165" class="img-circle" alt="decks ecologicos resistentes al exterior" src="images/deck-trascend/resistencia.gif">
					</span>
					<h3 class="bold">RESISTENCIA</h3>
					<div class="separator clearfix"></div>
					<p class="text-muted">RESISTENTE A LOS EFECTOS DE DESGASTE DE LA NATURALEZA.</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
					<span class="icon large circle">
						<img width="165" height="165" class="img-circle" alt="terminacion de los deck trex" src="images/deck-trascend/terminacion.gif">
					</span>
					<h3 class="bold">TERMINACIÓN</h3>
					<div class="separator clearfix"></div>
					<p class="text-muted">ACABADO DE VETAS DE MADERA DE ASPECTO NATURAL.</p>
				</div>
			</div>
		</div>
	</div>
</section>