<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

	<div class="container">
		<div class="row">
				<h3 class="text-center">COLORES DISPONIBLES</h3> 
				
			<!-- main start -->
			<!-- ================ -->
			<div class="main col-md-12">
				<div class="isotope-container row grid-space-10">
					<div class="col-md-4 col-sm-6 isotope-item web-design">
						<div class="image-box shadow bordered text-center mb-20">
							<div class="overlay-container">
								<img src="images/deck/castano.jpg" alt="color castano">
								<div class="overlay-top">
									<div class="text">
										<h3><a href="color-castano.php">Color Castaño</a></h3>
									</div>
								</div>
								<div class="overlay-bottom">
									<div class="links">
										<a href="color-castano.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-6 isotope-item web-design">
						<div class="image-box shadow bordered text-center mb-20">
							<div class="overlay-container">
								<img src="images/deck/gris-nevado.jpg" alt="color gris nevado">
								<div class="overlay-top">
									<div class="text">
										<h3><a href="color-gris-nevado.php">Color Gris Nevado</a></h3>
									</div>
								</div>
								<div class="overlay-bottom">
									<div class="links">
										<a href="color-gris-nevado.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-6 isotope-item web-design">
						<div class="image-box shadow bordered text-center mb-20">
							<div class="overlay-container">
								<img src="images/deck/lapacho.jpg" alt="color lapacho">
								<div class="overlay-top">
									<div class="text">
										<h3><a href="color-lapacho.php">Color Lapacho</a></h3>
									</div>
								</div>
								<div class="overlay-bottom">
									<div class="links">
										<a href="color-lapacho.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-6 isotope-item web-design">
						<div class="image-box shadow bordered text-center mb-20">
							<div class="overlay-container">
								<img src="images/deck/roble-montana.jpg" alt="color roble montana">
								<div class="overlay-top">
									<div class="text">
										<h3><a href="color-roble-montana.php">Color Roble Montaña</a></h3>
									</div>
								</div>
								<div class="overlay-bottom">
									<div class="links">
										<a href="color-roble-montana.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-6 isotope-item web-design">
						<div class="image-box shadow bordered text-center mb-20">
							<div class="overlay-container">
								<img src="images/deck/arena.jpg" alt="color arena">
								<div class="overlay-top">
									<div class="text">
										<h3><a href="color-arena.php">Color Arena</a></h3>
									</div>
								</div>
								<div class="overlay-bottom">
									<div class="links">
										<a href="color-arena.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- main end -->

		</div>
	</div>
</section>
<!-- main-container end -->