<section class="main-container">
  <div class="container">
    <div class="row">
      <h3 class="text-center">COLORES DISPONIBLES</h3>

      <!-- main start -->
      <!-- ================ -->
      <div class="main col-md-12">
        <div class="isotope-container row grid-space-10">
          <!-- Color -->
          <div class="col-md-3 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img
                  src="images/deck-select/blanco-smoke.jpg"
                  alt="deck select blanco smoke"
                />
                <div class="overlay-top">
                  <div class="text">
                    <h3>
                      <a href="deck-ecologico-select-blanco-smoke.php"
                        >Blanco Smoke</a
                      >
                    </h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a
                      href="deck-ecologico-select-blanco-smoke.php"
                      class="btn btn-gray-transparent btn-animated btn-sm"
                      >ver más<i class="pl-10 fa fa-arrow-right"></i
                    ></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Color end -->

          <!-- Color -->
          <div class="col-md-3 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img
                  src="images/deck-select/gris-mirage.jpg"
                  alt="deck select gris mirage"
                />
                <div class="overlay-top">
                  <div class="text">
                    <h3>
                      <a href="deck-ecologico-select-gris-mirage.php"
                        >Gris Mirage</a
                      >
                    </h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a
                      href="deck-ecologico-select-gris-mirage.php"
                      class="btn btn-gray-transparent btn-animated btn-sm"
                      >ver más<i class="pl-10 fa fa-arrow-right"></i
                    ></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Color end -->

          <!-- Color -->
          <div class="col-md-3 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img
                  src="images/deck-select/incienso.jpg"
                  alt="deck select incienso"
                />
                <div class="overlay-top">
                  <div class="text">
                    <h3>
                      <a href="deck-ecologico-select-incienso.php">Incienso</a>
                    </h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a
                      href="deck-ecologico-select-incienso.php"
                      class="btn btn-gray-transparent btn-animated btn-sm"
                      >ver más<i class="pl-10 fa fa-arrow-right"></i
                    ></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Color end -->

          <!-- Color -->
          <div class="col-md-3 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img
                  src="images/deck-select/maple.jpg"
                  alt="deck select maple"
                />
                <div class="overlay-top">
                  <div class="text">
                    <h3>
                      <a href="deck-ecologico-select-maple.php">Maple</a>
                    </h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a
                      href="deck-ecologico-select-maple.php"
                      class="btn btn-gray-transparent btn-animated btn-sm"
                      >ver más<i class="pl-10 fa fa-arrow-right"></i
                    ></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Color end -->
        </div>
      </div>
      <!-- main end -->
    </div>
  </div>
</section>
