<section class="section pv-40 clearfix">

	<div class="container text-center">
		<div class="row">
			<div class="col-sm-12">
				<h2><span class="light">CONOCÉ</span> LAS VENTAJAS</h2>
			</div>
			<div class="col-sm-6 col-md-4 padding_10px">
				<img class="centrar_imagen" src="images/deck-contour/ventajas/reciclado.gif" alt="deck de con materiales reciclados">
				<p class="padding_top_10px">Fabricados con un 95% <br>de materiales reciclados.</p>
			</div>

			<div class="col-sm-6 col-md-4 padding_10px">
				<img class="centrar_imagen" src="images/deck-contour/ventajas/colores.gif" alt="deck de variedad de colores">
				<p class="padding_top_10px">Variedad <br>de colores.</p>
			</div>

			<div class="col-sm-6 col-md-4 padding_10px">
				<img class="centrar_imagen" src="images/deck-contour/ventajas/garantia.gif" alt="deck de con 25 años de garantia">
				<p class="padding_top_10px">Garantía 25 años <br>Nivel residencial.</p>
			</div>

			<div class="col-sm-6 col-md-4 padding_10px">
				<img class="centrar_imagen" src="images/deck-contour/ventajas/mantenimiento.gif" alt="deck de sin mantenimiento">
				<p class="padding_top_10px">Fácil <br>mantenimiento.</p>
			</div>

			<div class="col-sm-6 col-md-4 padding_10px">
				<img class="centrar_imagen" src="images/deck-contour/ventajas/resistente.gif" alt="deck de resistente">
				<p class="padding_top_10px">Resistente a la decoloración, <br>y a las manchas.</p>
			</div>

			<div class="col-sm-6 col-md-4 padding_10px">
				<img class="centrar_imagen" src="images/deck-contour/ventajas/durable.gif" alt="deck de durabilidad">
				<p class="padding_top_10px">No se pudre, no se deforma, <br>ni se astilla.</p>
			</div>

		</div>
	</div>

</section>