<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

  <div class="container">
    <div class="row">
        <h3 class="text-center">COLORES DISPONIBLES</h3> 
        
      <!-- main start -->
      <!-- ================ -->
      <div class="main col-md-12">
        <div class="isotope-container row grid-space-10">

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-contour/lineas/gris-castor/trex-contour-decking-gris-castor-principal.jpg" alt="color gris castor">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-contour-plastico-pvc-gris-castor.php">Color Gris Castor</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-contour-plastico-pvc-gris-castor.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-contour/lineas/arena/arena-principal.jpg" alt="color arena">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-contour-plastico-pvc-arena.php">Color Arena</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-contour-plastico-pvc-arena.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-contour/lineas/marron-miel/marron-miel-principal.jpg" alt="color marron miel">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-contour-plastico-pvc-marron-miel.php">Color Marrón Miel</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-contour-plastico-pvc-marron-miel.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-contour/lineas/rojo-marroqui/rojo-marroqui-principal.jpg" alt="color rojo marroqui">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-contour-plastico-pvc-rojo-marroqui.php">Color Rojo Marroquí</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-contour-plastico-pvc-rojo-marroqui.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 isotope-item web-design">
            <div class="image-box shadow bordered text-center mb-20">
              <div class="overlay-container">
                <img src="images/deck-contour/lineas/marron-torino/marron-torino-principal.jpg" alt="color marron torino">
                <div class="overlay-top">
                  <div class="text">
                    <h3><a href="deck-ecologico-contour-plastico-pvc-marron-torino.php">Color Marrón Torino</a></h3>
                  </div>
                </div>
                <div class="overlay-bottom">
                  <div class="links">
                    <a href="deck-ecologico-contour-plastico-pvc-marron-torino.php" class="btn btn-gray-transparent btn-animated btn-sm">ver más<i class="pl-10 fa fa-arrow-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>


          
        </div>
      </div>
      <!-- main end -->

    </div>
  </div>
</section>
<!-- main-container end -->