<!-- footer start (Add "dark" class to #footer in order to enable dark footer) -->
<!-- ================ -->
<footer id="footer" class="clearfix dark">

	<!-- .footer start -->
	<!-- ================ -->
	<div class="footer">
		<div class="container">
			<div class="footer-inner">
				<div class="row">

					<div class="col-md-4">
						<div class="footer-content">
							<div class="logo-footer"><img id="logo-footer" src="images/footer/logo-nordeco-white.png" alt="logo nordeco"></div>
							<nav>
								<ul class="nav nav-pills nav-stacked">
									<li><a href="deck-ecologico-trascend.php">Deck</a></li>
									<li><a href="pisos.php">Pisos Vinílicos</a></li>
									<li><a href="zocalos.php">Zócalos</a></li>
									<li><a href="revestimientos-libre-mantenimiento.php">Revestimientos para pared</a></li>
									<li><a href="laminas.php">Láminas de piedra</a></li>
									<li><a href="muebles.php">Muebles de Exterior</a></li>
									<!-- <li><a href="inspiracion.php">Inspiración</a></li> -->
									<li><a href="deck-ecologico-color-roble.php">Portfolio</a></li>
									<li><a href="contacto.php">Contacto</a></li>
								</ul>
							</nav>
						</div>
					</div>

					<div class="col-md-4">
						<div class="footer-content">
							<h2 class="title">Newsletter</h2>
							<div class="separator-2"></div>
							<div class="media margin-clear">
								<?php include ("includes/newsletter_mailchimp.inc"); ?>
							</div>

						</div>
					</div>

					<div class="col-md-4">
						<div class="footer-content">
							<h2 class="title">Seguinos</h2>
							<div class="separator-2"></div>
							<p>Seguinos a través de instagram</p>
							<ul class="social-links circle animated-effect-1">
								<li class="instagram"><a target="_blank" href="https://www.instagram.com/nordeco___/"><i class="fa fa-instagram"></i></a></li>
								<li class="facebook"><a target="_blank" href="https://www.facebook.com/nordecodecks/"><i class="fa fa-facebook"></i></a></li>
							</ul>
							<div class="separator-2"></div>
							<ul class="list-icons">
								<li><a class="texto_verde" href="mailto:info@nordeco.com.ar"><i class="fa fa-envelope-o pr-10"></i>info@nordeco.com.ar</a></li>
							</ul>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
	<!-- .footer end -->

	<!-- .subfooter start -->
	<!-- ================ -->
	<div class="subfooter">
		<div class="container">
			<div class="subfooter-inner">
				<div class="row">
					<div class="col-md-12 text-center">
						<p class="text-center">Copyright <?php echo date('Y'); ?>
							<a target="_blank" href="http://nordeco.com.ar">Nordeco</a>.
							Todos los derechos reservados <br>
							Calle 56 Nº 4575 San Martín Buenos Aires Argentina <br>
						</p>
							<a href="tel:5491153117118"><i class="fa fa-phone" style="padding-right: 10px;"></i>11-5311-7118</a>.
					</div>
					<div class="col-md-12">
						<p class="libre">
							<a class="texto_blanco" target="_blank" href="http://librecomunicacion.net/">by LIBRE</a>
						</p> 
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- .subfooter end -->

</footer>
<!-- footer end -->