<!-- Galeria trascend start -->
<div class="container">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2>GALERÍA DE IMÁGENES</h2>
    </div>
  </div>
</div>

<section class="responsive slider margin-bottom-60">
  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/01-trex-enhance-beach-dune-atlanta-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/01-trex-enhance-beach-dune-atlanta-deck-ecologico.jpg" alt="deck de pvc premium trascend a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/02-trex-enhance-decking-beach-dune-closeup-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/02-trex-enhance-decking-beach-dune-closeup-deck-ecologico.jpg" alt="deck de pvc premium trascend b">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/03-trex-transcend-brew-club-retaurant-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/03-trex-transcend-brew-club-retaurant-deck-ecologico.jpg" alt="deck de pvc premium trascend c">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/04-trex-transcend-decking-spiced-rum-dock-norway-lake-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/04-trex-transcend-decking-spiced-rum-dock-norway-lake-deck-ecologico.jpg" alt="deck de pvc premium trascend d">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/05-trex-transcend-decking-gravel-path-vintage-lantern-pool-st-john-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/05-trex-transcend-decking-gravel-path-vintage-lantern-pool-st-john-deck-ecologico.jpg" alt="deck de pvc premium trascend e">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/06-trex-transcend-decking-lava-rock-spiced-rum-hot-tub-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/06-trex-transcend-decking-lava-rock-spiced-rum-hot-tub-deck-ecologico.jpg" alt="deck de pvc premium trascend f">
    </a>
  </article>

  <div class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/07-trex-transcend-decking-spiced-rum-boards-uk-closeup-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/07-trex-transcend-decking-spiced-rum-boards-uk-closeup-deck-ecologico.jpg" alt="deck de pvc premium trascend g">
    </a>
  </div>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/08-trex-transcend-porch-gravel-path-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/08-trex-transcend-porch-gravel-path-deck-ecologico.jpg" alt="deck de pvc premium trascend h">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/trex-transcend-decking-gravel-path-pool-florida-smart-home-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/trex-transcend-decking-gravel-path-pool-florida-smart-home-deck-ecologico.jpg" alt="deck de pvc premium trascend i">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/trex-transcend-decking-spiced-rum-closeup-elevations-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/trex-transcend-decking-spiced-rum-closeup-elevations-deck-ecologico.jpg" alt="deck de pvc premium trascend j">
    </a>
  </article>

  <div class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/trex-transcend-decking-tiki-torch-lava-rock-elevations-sunset-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/trex-transcend-decking-tiki-torch-lava-rock-elevations-sunset-deck-ecologico.jpg" alt="deck de pvc premium trascend l">
    </a>
  </div>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/trex-transcend-decking-tree-house-vintage-lantern-curves-pool-night-pergola-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/trex-transcend-decking-tree-house-vintage-lantern-curves-pool-night-pergola-deck-ecologico.jpg" alt="deck de pvc premium trascend m">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/trex-transcend-decking-tree-house-vintage-lantern-railing-curves-firepit-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/trex-transcend-decking-tree-house-vintage-lantern-railing-curves-firepit-deck-ecologico.jpg" alt="deck de pvc premium trascend n">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/trex-transcend-spiced-rum-hudson-deck-red-chairs-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/trex-transcend-spiced-rum-hudson-deck-red-chairs-deck-ecologico.jpg" alt="deck de pvc premium trascend o">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-trascend/galeria/grandes/trex-transcend-spiced-rum-lava-rock-elevations-step-view-deck-ecologico.jpg">
      <img src="images/deck-trascend/galeria/chicas/trex-transcend-spiced-rum-lava-rock-elevations-step-view-deck-ecologico.jpg" alt="deck de pvc premium trascend o">
    </a>
  </article>
</section>
<!-- Galeria trascend end -->