<!-- Galeria Pisos vinilicos start -->
<div class="container">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2>GALERÍA DE IMÁGENES</h2>
    </div>
  </div>
</div>

<section class="responsive slider margin-bottom-60">
  <article class="overlay-container">
    <a class="popup-img galeria" href="images/pisos-vinilicos/galeria/galeria-piso-vinilico-01-gr.jpg">
      <img src="images/pisos-vinilicos/galeria/galeria-piso-vinilico-01.jpg" alt="pisos vinilicos a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/pisos-vinilicos/galeria/galeria-piso-vinilico-02-gr.jpg">
      <img class="centrar_imagen" src="images/pisos-vinilicos/galeria/galeria-piso-vinilico-02.jpg" alt="pisos vinilicos b">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/pisos-vinilicos/galeria/galeria-piso-vinilico-03-gr.jpg">
      <img class="centrar_imagen" src="images/pisos-vinilicos/galeria/galeria-piso-vinilico-03.jpg" alt="pisos vinilicos c">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/pisos-vinilicos/galeria/galeria-piso-vinilico-04-gr.jpg">
      <img class="centrar_imagen" src="images/pisos-vinilicos/galeria/galeria-piso-vinilico-04.jpg" alt="pisos vinilicos d">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/pisos-vinilicos/galeria/galeria-piso-vinilico-05-gr.jpg">
      <img class="centrar_imagen" src="images/pisos-vinilicos/galeria/galeria-piso-vinilico-05.jpg" alt="pisos vinilicos f">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/pisos-vinilicos/galeria/galeria-piso-vinilico-07-gr.jpg">
      <img class="centrar_imagen" src="images/pisos-vinilicos/galeria/galeria-piso-vinilico-07.jpg" alt="pisos vinilicos h">
    </a>
  </article>
</section>
<!-- Galeria Pisos vinilicos end -->