<!-- Galeria Revestimientos start -->

<section class="galeria_rev">
  <section class="responsive slider margin-bottom-60">
    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-1-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-1.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -1" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-2-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-2.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -2" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-3-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-3.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -3" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-4-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-4.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -4" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-5-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-5.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -5" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-6-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-6.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -6" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-7-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-7.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -7" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-8-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-8.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -8" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-9-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-9.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -9" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-10-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-10.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -10" />
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/tetovinilico/galeria/galeria-teto-11-large.jpg"
        title="Cielorrasos Premium - Teto Vinílico - Argentina.">
        <img src="images/tetovinilico/galeria/galeria-teto-11.jpg"
          alt="Cielorrasos Premium - Teto Vinilico - Argentina -11" />
      </a>
    </article>
  </section>
</section>
<!-- Galeria Revestimientos end -->