<div class="container">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2>GALERÍA DE IMÁGENES</h2>
    </div>
  </div>
</div>

<!-- Galeria Logos Clientes start -->
<section class="responsive slider margin-bottom-60">
  <div>
    <img src="images/home/galeria-imagenes/galeria-a.jpg" alt="galeria a">
  </div>
  <div>
    <img src="images/home/galeria-imagenes/galeria-b.jpg" alt="galeria b">
  </div>
  <div>
    <img src="images/home/galeria-imagenes/galeria-c.jpg" alt="galeria c">
  </div>
  <div>
    <img src="images/home/galeria-imagenes/galeria-d.jpg" alt="galeria d">
  </div>
  <div>
    <img src="images/home/galeria-imagenes/galeria-e.jpg" alt="galeria e">
  </div>
  <div>
    <img src="images/home/galeria-imagenes/galeria-f.jpg" alt="galeria f">
  </div>
  <div>
    <img src="images/home/galeria-imagenes/galeria-g.jpg" alt="galeria g">
  </div>
  <div>
    <img src="images/home/galeria-imagenes/galeria-h.jpg" alt="galeria h">
  </div>
</section>
<!-- Galeria Logos Clientes end -->