<!-- Galeria contour start -->
<div class="container">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2>GALERÍA DE IMÁGENES</h2>
    </div>
  </div>
</div>

<section class="responsive slider margin-bottom-60">

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-a-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-a-ch.jpg" alt="deck ecologico trex enhance-a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-b-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-b-ch.jpg" alt="deck ecologico trex enhance-b">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-c-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-c-ch.jpg" alt="deck ecologico trex enhance-c">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-d-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-d-ch.jpg" alt="deck ecologico trex enhance-d">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-e-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-e-ch.jpg" alt="deck ecologico trex enhance-e">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-f-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-f-ch.jpg" alt="deck ecologico trex enhance-f">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-g-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-g-ch.jpg" alt="deck ecologico trex enhance-g">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-h-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-h-ch.jpg" alt="deck ecologico trex enhance-h">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-i-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-i-ch.jpg" alt="deck ecologico trex enhance-i">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-j-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-j-ch.jpg" alt="deck ecologico trex enhance-j">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-k-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-k-ch.jpg" alt="deck ecologico trex enhance-k">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-l-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-l-ch.jpg" alt="deck ecologico trex enhance-l">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-enhance/galeria/galeria-m-gr.jpg">
      <img src="images/deck-enhance/galeria/galeria-m-ch.jpg" alt="deck ecologico trex enhance-m">
    </a>
  </article>

</section>
<!-- Galeria contour end -->