<!-- Galeria contour start -->
<div class="container">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2>GALERÍA DE IMÁGENES</h2>
    </div>
  </div>
</div>

<section class="responsive slider margin-bottom-60">
  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-contour/galeria/01-clove-brown.jpg">
      <img src="images/deck-contour/galeria/chicas/01-clove-brown-contour-deck-ecologico-trex-ch.jpg" alt="deck contour a">
    </a>
  </article>
  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-contour/galeria/02-clove-brown.jpg">
      <img src="images/deck-contour/galeria/chicas/02-clove-brown-contour-deck-ecologico-trex-ch.jpg" alt="deck contour a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-contour/galeria/03-honey-brown.jpg">
      <img src="images/deck-contour/galeria/chicas/03-honey-brown-contour-deck-ecologico-trex-ch.jpg" alt="deck contour a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-contour/galeria/04-honey-brown.jpg">
      <img src="images/deck-contour/galeria/chicas/04-honey-brown-contour-deck-ecologico-trex-ch.jpg" alt="deck contour a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-contour/galeria/05-honey-brown.jpg">
      <img src="images/deck-contour/galeria/chicas/05-honey-brown-contour-deck-ecologico-trex-ch.jpg" alt="deck contour a">
    </a>
  </article>
    
  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-contour/galeria/06-russet-red.jpg">
      <img src="images/deck-contour/galeria/chicas/06-russet-red-contour-deck-ecologico-trex-ch.jpg" alt="deck contour a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-contour/galeria/07-pebble-grey.jpg">
      <img src="images/deck-contour/galeria/chicas/07-pebble-grey-contour-decks-ecologicos-trex-ch.jpg" alt="deck contour a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/deck-contour/galeria/08-pebble-grey.jpg">
      <img src="images/deck-contour/galeria/chicas/08-pebble-grey-contour-decks-ecologicos-trex-ch.jpg" alt="deck contour a">
    </a>
  </article>
</section>
<!-- Galeria contour end -->