<!-- Galeria Revestimientos start -->

<section class="galeria_rev">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h2>GALERÍA DE IMÁGENES</h2>
      </div>
    </div>
  </div>

  <section class="responsive slider margin-bottom-60">

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-a-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-a.jpg" alt="revestimientos para pared libre de mantenimiento a">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-b-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-b.jpg" alt="revestimientos para pared libre de mantenimiento b">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-c-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-c.jpg" alt="revestimientos para pared libre de mantenimiento c">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-d-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-d.jpg" alt="revestimientos para pared libre de mantenimiento d">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-e-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-e.jpg" alt="revestimientos para pared libre de mantenimiento e">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-f-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-f.jpg" alt="revestimientos para pared libre de mantenimiento f">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-g-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-g.jpg" alt="revestimientos para pared libre de mantenimiento g">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-h-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-h.jpg" alt="revestimientos para pared libre de mantenimiento h">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-i-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-i.jpg" alt="revestimientos para pared libre de mantenimiento i">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-j-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-j.jpg" alt="revestimientos para pared libre de mantenimiento j">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-k-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-k.jpg" alt="revestimientos para pared libre de mantenimiento k">
      </a>
    </article>

    <article class="overlay-container">
      <a class="popup-img galeria" href="images/revestimientos/galeria/revestimientos-l-gr.jpg" title="Revestimientos Para Pared libres de Mantenimiento">
        <img src="images/revestimientos/galeria/revestimientos-l.jpg" alt="revestimientos para pared libre de mantenimiento l">
      </a>
    </article>

    
  </section>
</section>
<!-- Galeria Revestimientos end -->