<!-- Galeria Muebles start -->
<div class="container">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2>GALERÍA DE IMÁGENES</h2>
    </div>
  </div>
</div>

<section class="responsive slider margin-bottom-60">
  <article class="overlay-container">
    <a class="popup-img galeria" href="images/muebles/galeria-muebles-a-gr.jpg" title="Reposeras">
      <img src="images/muebles/galeria-muebles-a.jpg" alt="muebles de exterior a">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/muebles/galeria-muebles-b-gr.jpg" title="Sillones y Mesas">
      <img src="images/muebles/galeria-muebles-b.jpg" alt="muebles de exterior b">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/muebles/galeria-muebles-c-gr.jpg" title="Reposeras">
      <img src="images/muebles/galeria-muebles-c.jpg" alt="muebles de exterior c">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/muebles/galeria-muebles-d-gr.jpg" title="Decorativos">
      <img src="images/muebles/galeria-muebles-d.jpg" alt="muebles de exterior d">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/muebles/galeria-muebles-e-gr.jpg" title="Sillones y Mesa">
      <img src="images/muebles/galeria-muebles-e.jpg" alt="muebles de exterior e">
    </a>
  </article>

  <article class="overlay-container">
    <a class="popup-img galeria" href="images/muebles/galeria-muebles-f-gr.jpg" title="Sillones y Mesa">
      <img src="images/muebles/galeria-muebles-f.jpg" alt="muebles de exterior f">
    </a>
  </article>
</section>
<!-- Galeria Muebles end -->