<section class="section dark-bg clearfix">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="call-to-action text-center">
					<div class="row">
						<div class="col-sm-8">
							<h2 class="title">NECESITAS MAS INFORMACION?</h2>
							<p>Nuestro equipo especializado está a tu disposición para cualquier consulta. Contactanos!</p>
						</div>
						<div class="col-sm-4">
							<br>
							<p><a href="contacto.php" class="btn btn-lg btn-gray-transparent btn-animated">Contactar<i class="fa fa-file-text pl-20"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>