<section class="section fondo_verde clearfix">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-8">
        <h2 class="color_blanco">¿NECESITÁS MÁS INFORMACIÓN?</h2>
      </div>
      <div class="col-md-4">
        <a
          href="./contacto.php"
          target="blank"
          class="btn btn-verde btn-animated"
          >COTIZAR<i class="fa fa-arrow-right"></i
        ></a>
      </div>
    </div>
  </div>
</section>
