<!-- banner start -->
<!-- ================ -->
<div class="pv-40 banner light-gray-bg">
	<div class="container clearfix">

		<!-- slideshow start -->
		<!-- ================ -->
		<div class="slideshow">
			
			<!-- slider revolution start -->
			<!-- ================ -->
			<div class="slider-banner-container">
				<div class="slider-banner-boxedwidth">
					<ul class="slides">
						<!-- slide 1 start -->
						<!-- ================ -->
						<li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Deck Ecologicos 1">
						
						<!-- main image -->
						<img src="images/deck/deck-ecologico-a.jpg" alt="deck ecologico a" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">
						</li>
						<!-- slide 1 end -->

						<!-- slide 2 start -->
						<!-- ================ -->
						<li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Deck Ecologicos 2">
						
						<!-- main image -->
						<img src="images/deck/deck-ecologico-b.jpg" alt="deck ecologico b" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">
						</li>
						<!-- slide 2 end -->

						<!-- slide 3 start -->
						<!-- ================ -->
						<li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Deck Ecologicos 3">
						
						<!-- main image -->
						<img src="images/deck/deck-ecologico-c.jpg" alt="deck ecologico c" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">
						</li>
						<!-- slide 3 end -->
					</ul>
					<div class="tp-bannertimer"></div>
				</div>
			</div>
			<!-- slider revolution end -->

		</div>
		<!-- slideshow end -->

	</div>
</div>
<!-- banner end -->