<!-- banner start -->
<!-- ================ -->
<div class="banner clearfix">

	<!-- slideshow start -->
	<!-- ================ -->
	<div class="slideshow">

		<!-- slider revolution start -->
		<!-- ================ -->
		<div class="slider-revolution-5-container">
			<div id="slider-banner-fullwidth" class="slider-banner-fullwidth rev_slider" data-version="5.0">
				<ul class="slides">
					<!-- slide 1 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Cantos PVC estandar">

					<!-- main image -->
					<img src="images/home/slides-deck-ecologicos-01.jpg" alt="deck ecologico 1" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover"  class="rev-slidebg">

					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="5000">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white tipo_3em bold"
						data-x="center"
						data-y="50"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;o:0;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						DECKS ECOLÓGICOS
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption medium_white text-center hidden-xs tipo_2_5em"
						data-x="center"
						data-y="100"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">LÍNEA ESTÁNDAR - NORDECO
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption large_white text-center tp-resizeme hidden-xs"
						data-x="center"
						data-y="150"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="180"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"><strong>En Cantofil te ofrecemos un amplio catálogo de cantos de PVC,</strong> <br>
						en conjunción con los diseños de las colecciones de placas <br>
						de las marcas más importantes del mercado.
					</div>

					<!-- LAYER NR. 5 -->
					<div class="tp-caption small_white text-center"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
							<a href="cantos-pvc-estandar.php" class="btn btn-bordo btn-animated margin-clear">VER MAS<i class="fa fa-arrow-right"></i></a>
					</div>

					</li>
					<!-- slide 1 end -->


					<!-- slide 2 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Cantos PVC premium">

					<!-- main image -->
					<img src="images/home/slides-deck-ecologicos-02.jpg" alt="decks ecologicos 02" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover"  class="rev-slidebg">

					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="5000">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white tipo_3em bold"
						data-x="center"
						data-y="50"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;o:0;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						CANTOS DE PVC
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption medium_white text-center hidden-xs tipo_2_5em"
						data-x="center"
						data-y="100"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">LÍNEA PREMIUM - CANPLAST
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption large_white text-center tp-resizeme hidden-xs"
						data-x="center"
						data-y="150"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="180"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">Finalizá tus creaciones con un acabado de <strong>máxima calidad</strong> <br>
						para los distintos tipos de mobiliarios.
					</div>

					<!-- LAYER NR. 5 -->
					<div class="tp-caption small_white text-center"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
							<a href="cantos-pvc-premium.php" class="btn btn-bordo btn-animated margin-clear">VER MAS<i class="fa fa-arrow-right"></i></a>
					</div>

					</li>
					<!-- slide 2 end -->

					<!-- slide 3 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Pisos Vinilicos">

					<!-- main image -->
					<img src="images/home/slides-muebles-aluminio-03" alt="muebles de aluminio" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover"  class="rev-slidebg">

					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="5000">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white tipo_3em bold"
						data-x="center"
						data-y="50"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;o:0;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						PISOS VINÍLICOS
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption medium_white text-center hidden-xs tipo_2_5em"
						data-x="center"
						data-y="100"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">PISOPLAST
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption large_white text-center tp-resizeme hidden-xs"
						data-x="center"
						data-y="150"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="180"
						data-start="1300"
						data-width="950"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"><strong>Los pisos vinílicos Pisoplast</strong>, son ideales para entornos comerciales y domésticos, <br>
						desarrollados con materiales de primera calidad.
					</div>

					<!-- LAYER NR. 5 -->
					<div class="tp-caption small_white text-center"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
							<a href="pisos-vinilicos.php" class="btn btn-bordo btn-animated margin-clear">VER MAS<i class="fa fa-arrow-right"></i></a>
					</div>

					</li>
					<!-- slide 3 end -->

					<!-- slide 4 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Deck Trex Trascend">

					<!-- main image -->
					<img src="images/home/slides-pisos-vinilicos-04.jpg" alt="pisos vinilicos" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover"  class="rev-slidebg">

					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="5000">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white tipo_3em bold"
						data-x="center"
						data-y="50"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;o:0;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						DECKS ECOLÓGICOS
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption medium_white text-center hidden-xs tipo_2_5em"
						data-x="center"
						data-y="100"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">LÍNEA PREMIUM - TREX TRASCEND
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption large_white text-center tp-resizeme hidden-xs"
						data-x="center"
						data-y="150"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="180"
						data-start="1300"
						data-width="950"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"><strong>Decks ecológicos</strong> con tecnología de alto tránsito <br>
						y acabado de vetas de aspecto natural
					</div>

					<!-- LAYER NR. 5 -->
					<div class="tp-caption small_white text-center"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
							<a href="deck-ecologico-trascend-plastico-pvc-premium.php" class="btn btn-bordo btn-animated margin-clear">VER MAS<i class="fa fa-arrow-right"></i></a>
					</div>

					</li>
					<!-- slide 4 end -->

				</ul>
				<div class="tp-bannertimer"></div>
			</div>
		</div>
		<!-- slider revolution end -->

	</div>
	<!-- slideshow end -->

</div>
<!-- banner end -->
