<section class="full-width-section pv-40 light-gray-bg border-clear">
	<div class="full-text-container text-right left light-gray-bg border-clear">
		<h2>TECNOLOGÍA CLICK</h2>
		<h3>Eliminación de adhesivo</h3>
		<br class="hidden-sm hidden-xs">

		<div class="feature-box-2 right margin-clear">
			<span class="icon without-bg"><img src="images/pisos-vinilicos/tilde_verde.png" alt="tilde"></span>
			<div class="body">
				<h4>Instalación perfecta.</h4>
				<p>Asegura estabilidad y perfección.</p>
				<div class="separator-3 visible-lg"></div>
			</div>
		</div>

		<div class="feature-box-2 right margin-clear">
			<span class="icon without-bg"><img src="images/pisos-vinilicos/tilde_verde.png" alt="tilde"></span>
			<div class="body">
				<h4>Impermeable.</h4>
				<p>Contribución a la impermeabilidad.</p>
				<div class="separator-3 visible-lg"></div>
			</div>
		</div>

		<div class="feature-box-2 right margin-clear">
			<span class="icon without-bg"><img src="images/pisos-vinilicos/tilde_verde.png" alt="tilde"></span>
			<div class="body">
				<h4>Agilidad.</h4>
				<p>Rápida instalación sin necesidad de mano de obra especializada.</p>
				<div class="separator-3 visible-lg"></div>
			</div>
		</div>

		<div class="feature-box-2 right margin-clear">
			<span class="icon without-bg"><img src="images/pisos-vinilicos/tilde_verde.png" alt="tilde"></span>
			<div class="body">
				<h4>Simplicidad.</h4>
				<p>Bordes que facilitan su colocación en dos simples pasos.</p>
				<div class="separator-3 visible-lg"></div>
			</div>
		</div>

	</div>
	<div class="clearfix">
		<img class="object-non-visible animated object-visible slideInDown" data-animation-effect="slideInDown" data-effect-delay="100" src="images/pisos-vinilicos/tecnologia-click.jpg" alt="tecnologia click">
	</div>
</section>