<section class="section pv-40 clearfix">

	<div class="container text-center">
		<div class="row">
			<div class="col-sm-12">
				<h2>ASPECTOS Y VENTAJAS</h2>
			</div>
			<div class="col-sm-6 col-md-3 padding_10px">
				<img class="centrar_imagen" src="images/pisos-vinilicos/aspectos-ventajas/01-facil-de-instalar-pisos-vinilicos.gif" alt="pisos vinilicos facil de instalar">
				<p class="padding_top_10px">Fácil de instalar, <br>limpiar y mantener.</p>
			</div>

			<div class="col-sm-6 col-md-3 padding_10px">
				<img class="centrar_imagen" src="images/pisos-vinilicos/aspectos-ventajas/02-resistente-golpes-pisos-vinilicos.gif" alt="pisos vinilicos resistente a golpes">
				<p class="padding_top_10px">Resistente <br>a golpes y arañazos.</p>
			</div>

			<div class="col-sm-6 col-md-3 padding_10px">
				<img class="centrar_imagen" src="images/pisos-vinilicos/aspectos-ventajas/03-resistente-al-agua-pisos-vinilicos.gif" alt="pisos vinilicos resistente al agua">
				<p class="padding_top_10px">Resistente 100% al agua, <br>ideal en baños y cocinas.</p>
			</div>

			<div class="col-sm-6 col-md-3 padding_10px">
				<img class="centrar_imagen" src="images/pisos-vinilicos/aspectos-ventajas/04-fabricado-con-meteriales-pisos-vinilicos.gif" alt="pisos vinilicos con materiales reciclados">
				<p class="padding_top_10px">Fabricado <br>con materiales reciclados.</p>
			</div>
		</div>
	</div>

	<div class="container text-center">
		<div class="row">
			<div class="col-sm-6 col-md-3 padding_10px">
				<img class="centrar_imagen" src="images/pisos-vinilicos/aspectos-ventajas/05-no-requiere-productos-quimicos-pisos-vinilicos.gif" alt="pisos vinilicos libre de mantenimiento">
				<p class="padding_top_10px">No requiere de productos químicos <br>agresivos para su limpieza.</p>
			</div>

			<div class="col-sm-6 col-md-3 padding_10px">
				<img class="centrar_imagen" src="images/pisos-vinilicos/aspectos-ventajas/06-aplicable-sobre-superficies-pisos-vinilicos.gif" alt="pisos vinilicos Aplicable sobre superficies existentes.">
				<p class="padding_top_10px">Aplicable sobre <br>superficies existentes.</p>
			</div>

			<div class="col-sm-6 col-md-3 padding_10px">
				<img class="centrar_imagen" src="images/pisos-vinilicos/aspectos-ventajas/07-aislamiento-acustico-pisos-vinilicos.gif" alt="pisos vinilicos resistente aislamiento acustico">
				<p class="padding_top_10px">Aislamiento acústico y térmico, <br>ideal para pisos radiantes.</p>
			</div>

			<div class="col-sm-6 col-md-3 padding_10px">
				<img class="centrar_imagen" src="images/pisos-vinilicos/aspectos-ventajas/08-antideslizante-pisos-vinilicos.gif" alt="pisos vinilicos antideslizantes">
				<p class="padding_top_10px">Antideslizante.</p>
			</div>
		</div>
	</div>
</section>