<!-- banner start -->
<!-- ================ -->
<div class="banner clearfix">

	<!-- slideshow start -->
	<!-- ================ -->
	<div class="slideshow">

		<!-- slider revolution start -->
		<!-- ================ -->
		<div class="slider-revolution-5-container">
			<div id="slider-banner-fullwidth" class="slider-banner-fullwidth rev_slider" data-version="5.0">
				<ul class="slides">
					<!-- slide 1 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Pisos vinílicos">

					<!-- main image -->
					<img src="images/pisos-vinilicos/slide-spc/1-slide-piso-vinilico.jpg" alt="pisos vinilicos ssitema click" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover" class="rev-slidebg">

					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="450">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white"
						data-x="center"
						data-y="110"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">Variedad de colores
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption text-center large_white tp-resizeme hidden-xs"
						data-x="center"
						data-y="155"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="190"
						data-start="1300"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">Consulte por colores nuestro catálogo.
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption small_white text-center hidden-xs"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<a href="contacto.php" class="btn btn-default btn-animated margin-clear">Solicita mas info<i class="fa fa-envelope"></i></a>

					</li>
					<!-- slide 1 end -->

					<!-- slide 2 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Pisos vinílicos">

					<!-- main image -->
					<img src="images/pisos-vinilicos/slide-spc/2-slide-piso-vinilico.jpg" alt="pisos vinilicos sin adhesivo" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover" class="rev-slidebg">

					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="450">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white"
						data-x="center"
						data-y="110"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">Ventajas de utilizar pisos vinílicos
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption text-center large_white tp-resizeme hidden-xs"
						data-x="center"
						data-y="155"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="190"
						data-start="1300"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">Rápida aplicación, fácil mantenimiento.
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption small_white text-center hidden-xs"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<a href="contacto.php" class="btn btn-default btn-animated margin-clear">Solicita mas info<i class="fa fa-envelope"></i></a>
					</div>

					</li>
					<!-- slide 2 end -->

					<!-- slide 3 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Pisos vinílicos">

					<!-- main image -->
					<img src="images/pisos-vinilicos/slide-spc/3-slide-piso-vinilico.jpg" alt="pisos vinilicos variedad" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover" class="rev-slidebg">

					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="450">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white"
						data-x="center"
						data-y="110"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">Resistente al agua 100%
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption text-center large_white tp-resizeme hidden-xs"
						data-x="center"
						data-y="155"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="190"
						data-start="1300"
						data-width="850"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">Aplicable sobre <br>superficies existentes.
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption small_white text-center hidden-xs"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<a href="contacto.php" class="btn btn-default btn-animated margin-clear">Solicita mas info<i class="fa fa-envelope"></i></a>
					</div>

					</li>
					<!-- slide 3 end -->

				</ul>
				<div class="tp-bannertimer"></div>
			</div>
		</div>
		<!-- slider revolution end -->

	</div>
	<!-- slideshow end -->

</div>
<!-- banner end -->
