<!-- banner start -->
<!-- ================ -->
<div class="banner clearfix">

	<!-- slideshow start -->
	<!-- ================ -->
	<div class="slideshow">

		<!-- slider revolution start -->
		<!-- ================ -->
		<div class="slider-revolution-5-container">
			<div id="slider-banner-fullwidth" class="slider-banner-fullwidth rev_slider" data-version="5.0">
				<ul class="slides">
					<!-- slide 1 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Deck Ecológico estándar">

					<!-- main image -->
					<img src="images/deck-contour/slide/1-slide-deck-ecologico-contour.jpg" alt="deck ecologico contour a" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover"  class="rev-slidebg">

					<!-- Transparent Background -->
					<!-- <div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="5000">
					</div> -->

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white tipo_3em bold"
						data-x="center"
						data-y="50"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;o:0;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">DECKS ECOLÓGICOS</span>
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption medium_white text-center hidden-xs tipo_2_5em"
						data-x="center"
						data-y="100"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">LÍNEA CONTOUR - NORDECO</span>
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption large_white text-center tp-resizeme hidden-xs"
						data-x="center"
						data-y="150"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="180"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">Fabricados con un 95% de materiales reciclados.</span>
					</div>

					<!-- LAYER NR. 5 -->
					<div class="tp-caption small_white text-center"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
							<a href="contacto.php" class="btn btn-verde btn-animated margin-clear">Solicita mas info<i class="fa fa-arrow-right"></i></a>
					</div>

					</li>
					<!-- slide 1 end -->

					<!-- slide 2 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Decks Ecológicos estándar">

					<!-- main image -->
					<img src="images/deck-contour/slide/2-slide-deck-ecologico-contour.jpg" alt="deck ecologico contour b" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover"  class="rev-slidebg">

					<!-- Transparent Background -->
					<!-- <div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="5000">
					</div> -->

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white tipo_3em bold"
						data-x="center"
						data-y="50"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;o:0;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">DECKS ECOLÓGICOS</span>
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption medium_white text-center hidden-xs tipo_2_5em"
						data-x="center"
						data-y="100"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">LÍNEA CONTOUR - NORDECO</span>
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption large_white text-center tp-resizeme hidden-xs"
						data-x="center"
						data-y="150"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="180"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">No se pudre, no se deforma, ni se astilla.</span>
					</div>

					<!-- LAYER NR. 5 -->
					<div class="tp-caption small_white text-center"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
							<a href="contacto.php" class="btn btn-verde btn-animated margin-clear">Solicita mas info<i class="fa fa-arrow-right"></i></a>
					</div>

					</li>
					<!-- slide 2 end -->

					<!-- slide 3 start -->
					<!-- ================ -->
					<li data-transition="slideleft" data-slotamount="default" data-masterspeed="default" data-title="Decks Ecológicos estándar">

					<!-- main image -->
					<img src="images/deck-contour/slide/3-slide-deck-ecologico-contour.jpg" alt="deck ecologico contour c" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover"  class="rev-slidebg">

					<!-- Transparent Background -->
					<!-- <div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="center"
						data-start="0"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:600;e:Power2.easeInOut;"
						data-transform_out="o:0;s:600;"
						data-width="5000"
						data-height="5000">
					</div> -->

					<!-- LAYER NR. 1 -->
					<div class="tp-caption text-center large_white tipo_3em bold"
						data-x="center"
						data-y="50"
						data-start="1000"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;o:0;s:2150;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">DECKS ECOLÓGICOS</span>
					</div>

					<!-- LAYER NR. 2 -->
					<div class="tp-caption medium_white text-center hidden-xs tipo_2_5em"
						data-x="center"
						data-y="100"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">LÍNEA CONTOUR - NORDECO</span>
					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption large_white text-center tp-resizeme hidden-xs"
						data-x="center"
						data-y="150"
						data-start="1300"
						data-width="500"
						data-transform_idle="o:1;"
						data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
							<div class="separator light"></div>
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption medium_white text-center hidden-xs"
						data-x="center"
						data-y="180"
						data-start="1300"
						data-width="750"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1700;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
						<span class="sombras_baner_home">Resistente a la decoloración, y a las manchas.</span>
					</div>

					<!-- LAYER NR. 5 -->
					<div class="tp-caption small_white text-center"
						data-x="center"
						data-y="310"
						data-start="1600"
						data-width="650"
						data-transform_idle="o:1;"
						data-transform_in="y:[100%];sX:1;sY:1;s:1400;e:Power4.easeInOut;"
						data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
						data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
						data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
							<a href="contacto.php" class="btn btn-verde btn-animated margin-clear">Solicita mas info<i class="fa fa-arrow-right"></i></a>
					</div>

					</li>
					<!-- slide 3 end -->

				</ul>
				<div class="tp-bannertimer"></div>
			</div>
		</div>
		<!-- slider revolution end -->

	</div>
	<!-- slideshow end -->

</div>
<!-- banner end -->
