<!-- banner start -->
<!-- ================ -->
<div class="pv-40 banner light-gray-bg">
	<div class="clearfix">

		<!-- slideshow start -->
		<!-- ================ -->
		<div class="slideshow">
			
			<!-- slider revolution start -->
			<!-- ================ -->
			<div class="slider-banner-container">
				<div class="slider-banner-boxedwidth">
					<ul class="slides">
						<!-- slide 1 start -->
						<!-- ================ -->
						<li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Sillones y reposeras">
						
						<!-- main image -->
						<img src="images/muebles/slide-muebles-a.jpg" alt="Sillones y reposeras" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">
						</li>
						<!-- slide 1 end -->

						<!-- slide 2 start -->
						<!-- ================ -->
						<li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Pérgolas y reposeras">
						
						<!-- main image -->
						<img src="images/muebles/slide-muebles-b.jpg" alt="Muebles de Exterior b" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">
						</li>
						<!-- slide 2 end -->

						<!-- slide 3 start -->
						<!-- ================ -->
						<li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Mesas y sillas">
						
						<!-- main image -->
						<img src="images/muebles/slide-muebles-c.jpg" alt="Muebles de Exterior c" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">
						</li>
						<!-- slide 3 end -->
					</ul>
					<div class="tp-bannertimer"></div>
				</div>
			</div>
			<!-- slider revolution end -->

		</div>
		<!-- slideshow end -->

	</div>
</div>
<!-- banner end -->