<!-- Slide Home start -->
<!-- ================ -->
<div class="banner clearfix">

	<!-- slideshow start -->
	<!-- ================ -->
	<div class="slideshow">
		
		<!-- slider revolution start -->
		<!-- ================ -->
		<div class="slider-banner-container">
			<div class="slider-banner-fullwidth">
				<ul class="slides">
					<!-- slide 1 start -->
					<!-- ================ -->
					<li data-transition="fade" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Decks Ecológicos  - Trex Trascend">
					
						<!-- main image -->
						<img src="images/home/slides-deck-ecologicos-01.jpg" alt="deck ecologico" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">

						<!-- Transparent Background -->
						<div class="tp-caption"
							data-x="center"
							data-y="bottom"
							data-speed="600"
							data-start="0">
						</div>

						<!-- LAYER NR. 1 -->
						<div class="tp-caption sfb fadeout large_white"
							data-x="left"
							data-y="110"
							data-speed="500"
							data-start="1000"
							data-easing="easeOutQuad"><span class="sombras_baner_home">DECK ECOLÓGICO PREMIUM</span>
						</div>	

						<!-- LAYER NR. 2 -->
						<div class="tp-caption sfb fadeout large_white tp-resizeme hidden-xs"
							data-x="left"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"><div class="sombras_baner_home separator-2 light">TREX TRASCEND</div>
						</div>	

						<!-- LAYER NR. 3 -->
						<div class="tp-caption sfb fadeout medium_white hidden-xs"
							data-x="left"
							data-y="220"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"
							data-endspeed="600"><span class="sombras_baner_home">Decks ecológicos con tecnología de alto tránsito <br>y acabado de vetas de aspecto natural. <br>DECKS LIBRES DE MANTENIMIENTO</span>
						</div>

						<!-- LAYER NR. 4 -->
						<div class="tp-caption sfb fadeout small_white"
							data-x="left"
							data-y="340"
							data-speed="500"
							data-start="1600"
							data-easing="easeOutQuad"
							data-endspeed="600"><a href="deck-ecologico-trascend.php" class="btn radius-50 btn-dark btn-animated">Ver más<i class="fa fa-arrow-right"></i></a> <span class="pl-5 pr-5">o</span> <a href="contacto.php" class="btn radius-50 btn-default btn-animated">Contáctenos <i class="fa fa-envelope"></i></a>
						</div>

					</li>
					<!-- slide 1 end -->

					<!-- slide 2 start -->
					<!-- ================ -->
					<li data-transition="fade" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Decks Ecológicos  - Trex Contour">
					
						<!-- main image -->
						<img src="images/home/slides-deck-ecologicos-02.jpg" alt="deck ecologico" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">

						<!-- Transparent Background -->
						<div class="tp-caption"
							data-x="center"
							data-y="bottom"
							data-speed="600"
							data-start="0">
						</div>

						<!-- LAYER NR. 1 -->
						<div class="tp-caption sfb fadeout text-center large_white"
							data-x="center"
							data-y="110"
							data-speed="500"
							data-start="1000"
							data-easing="easeOutQuad"><span class="sombras_baner_home">DECK ECOLÓGICO ESTÁNDAR</span>
						</div>	

						<!-- LAYER NR. 2 -->
						<div class="tp-caption sfb fadeout text-center large_white tp-resizeme hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"><div class="sombras_baner_home separator-2 light">TREX CONTOUR</div>
						</div>	

						<!-- LAYER NR. 3 -->
						<div class="tp-caption sfb fadeout text-center medium_white hidden-xs"
							data-x="center"
							data-y="220"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"
							data-endspeed="600"><span class="sombras_baner_home">Decks ecológicos con tecnología de alto tránsito <br>y acabado con vetas de aspecto natural.<br>DECKS LIBRES DE MANTENIMIENTO</span>
						</div>

						<!-- LAYER NR. 4 -->
						<div class="tp-caption sfb fadeout text-center small_white"
							data-x="center"
							data-y="340"
							data-speed="500"
							data-start="1600"
							data-easing="easeOutQuad"
							data-endspeed="600"><a href="deck-ecologico-contour.php" class="btn radius-50 btn-dark btn-animated">Ver más<i class="fa fa-arrow-right"></i></a> <span class="pl-5 pr-5">o</span> <a href="contacto.php" class="btn radius-50 btn-default btn-animated">Contáctenos <i class="fa fa-envelope"></i></a>
						</div>

					</li>
					<!-- slide 2 end -->

					<!-- slide 3 start -->
					<!-- ================ -->
					<li data-transition="fade" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Muebles de Aluminio para Exterior">
					
						<!-- main image -->
						<img src="images/home/slides-muebles-aluminio-03.jpg" alt="muebles de aluminio" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">

						<!-- Transparent Background -->
						<div class="tp-caption"
							data-x="center"
							data-y="bottom"
							data-speed="600"
							data-start="0">
						</div>

						<!-- LAYER NR. 1 -->
						<div class="tp-caption sfb fadeout text-center large_white"
							data-x="center"
							data-y="110"
							data-speed="500"
							data-start="1000"
							data-easing="easeOutQuad"><span class="sombras_baner_home separator-2 light">MUEBLES DE EXTERIOR</span>
						</div>	

						<!-- LAYER NR. 2 -->
						<!-- <div class="tp-caption sfb fadeout text-center large_white tp-resizeme hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"><div class="sombras_baner_home separator-2 light">TREX CONTOUR</div>
						</div> -->	

						<!-- LAYER NR. 3 -->
						<div class="tp-caption sfb fadeout text-center medium_white hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"
							data-endspeed="600">
							<span class="sombras_baner_home">
								Fabricados en una aleación de aluminio especial, <br>
								mediante un proceso de anodizado crea un material <br>
								que no se daña y es inoxidable. Su acabado es suave y uniforme.
							</span>
						</div>

						<!-- LAYER NR. 4 -->
						<div class="tp-caption sfb fadeout text-center small_white"
							data-x="center"
							data-y="280"
							data-speed="500"
							data-start="1600"
							data-easing="easeOutQuad"
							data-endspeed="600"><a href="muebles.php" class="btn radius-50 btn-dark btn-animated">Ver más<i class="fa fa-arrow-right"></i></a> <span class="pl-5 pr-5">o</span> <a href="contacto.php" class="btn radius-50 btn-default btn-animated">Contáctenos <i class="fa fa-envelope"></i></a>
						</div>

					</li>
					<!-- slide 3 end -->

					<!-- slide 4 start -->
					<!-- ================ -->
					<li data-transition="fade" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Pisos Vinílicos">
					
						<!-- main image -->
						<img src="images/home/slides-pisos-vinilicos-04.jpg" alt="muebles de aluminio" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">

						<!-- Transparent Background -->
						<div class="tp-caption"
							data-x="center"
							data-y="bottom"
							data-speed="600"
							data-start="0">
						</div>

						<!-- LAYER NR. 1 -->
						<div class="tp-caption sfb fadeout text-center large_white"
							data-x="center"
							data-y="110"
							data-speed="500"
							data-start="1000"
							data-easing="easeOutQuad"><span class="sombras_baner_home separator-2 light">PISOS VINÍLICOS</span>
						</div>	

						<!-- LAYER NR. 2 -->
						<!-- <div class="tp-caption sfb fadeout text-center large_white tp-resizeme hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"><div class="sombras_baner_home separator-2 light">TREX CONTOUR</div>
						</div> -->	

						<!-- LAYER NR. 3 -->
						<div class="tp-caption sfb fadeout text-center medium_white hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"
							data-endspeed="600">
							<span class="sombras_baner_home">
								Los pisos flotantes Pisoplast, son ideales para entornos comerciales y domésticos. <br>
								Desarrollados con materiales de primera calidad.
							</span>
						</div>

						<!-- LAYER NR. 4 -->
						<div class="tp-caption sfb fadeout text-center small_white"
							data-x="center"
							data-y="250"
							data-speed="500"
							data-start="1600"
							data-easing="easeOutQuad"
							data-endspeed="600"><a href="pisos.php" class="btn radius-50 btn-dark btn-animated">Ver más<i class="fa fa-arrow-right"></i></a> <span class="pl-5 pr-5">o</span> <a href="contacto.php" class="btn radius-50 btn-default btn-animated">Contáctenos <i class="fa fa-envelope"></i></a>
						</div>

					</li>
					<!-- slide 4 end -->

					<!-- slide 5 start -->
					<!-- ================ -->
					<li data-transition="fade" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Láminas">
					
						<!-- main image -->
						<img src="images/home/slide-laminas.jpg" alt="laminas de piedra" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">

						<!-- Transparent Background -->
						<div class="tp-caption"
							data-x="center"
							data-y="bottom"
							data-speed="600"
							data-start="0">
						</div>

						<!-- LAYER NR. 1 -->
						<div class="tp-caption sfb fadeout text-center large_white"
							data-x="center"
							data-y="110"
							data-speed="500"
							data-start="1000"
							data-easing="easeOutQuad"><span class="sombras_baner_home separator-2 light">LÁMINAS DE PIEDRA</span>
						</div>	

						<!-- LAYER NR. 2 -->
						<!-- <div class="tp-caption sfb fadeout text-center large_white tp-resizeme hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"><div class="sombras_baner_home separator-2 light">TREX CONTOUR</div>
						</div> -->	

						<!-- LAYER NR. 3 -->
						<div class="tp-caption sfb fadeout text-center medium_white hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"
							data-endspeed="600">
							<span class="sombras_baner_home">
								Las láminas de piedra flexible son un revestimiento moderno,<br>de fácil aplicación, ligero y con posibilidades ilimitadas. .
							</span>
						</div>

						<!-- LAYER NR. 4 -->
						<div class="tp-caption sfb fadeout text-center small_white"
							data-x="center"
							data-y="250"
							data-speed="500"
							data-start="1600"
							data-easing="easeOutQuad"
							data-endspeed="600"><a href="laminas.php" class="btn radius-50 btn-dark btn-animated">Ver más<i class="fa fa-arrow-right"></i></a> <span class="pl-5 pr-5">o</span> <a href="contacto.php" class="btn radius-50 btn-default btn-animated">Contáctenos <i class="fa fa-envelope"></i></a>
						</div>

					</li>
					<!-- slide 5 end -->

					<!-- slide 5 start -->
					<!-- ================ -->
					<li data-transition="fade" data-slotamount="1" data-masterspeed="500" data-saveperformance="on" data-title="Revestimientos">
					
						<!-- main image -->
						<img src="images/home/slide-revestimientos.jpg" alt="revestimientos de pared" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">

						<!-- Transparent Background -->
						<div class="tp-caption"
							data-x="center"
							data-y="bottom"
							data-speed="600"
							data-start="0">
						</div>

						<!-- LAYER NR. 1 -->
						<div class="tp-caption sfb fadeout text-center large_white"
							data-x="center"
							data-y="110"
							data-speed="500"
							data-start="1000"
							data-easing="easeOutQuad"><span class="sombras_baner_home separator-2 light">REVESTIMIENTOS LIBRES DE MANTENIMIENTO</span>
						</div>	

						<!-- LAYER NR. 2 -->
						<!-- <div class="tp-caption sfb fadeout text-center large_white tp-resizeme hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"><div class="sombras_baner_home separator-2 light">TREX CONTOUR</div>
						</div> -->	

						<!-- LAYER NR. 3 -->
						<div class="tp-caption sfb fadeout text-center medium_white hidden-xs"
							data-x="center"
							data-y="170"
							data-speed="500"
							data-start="1300"
							data-easing="easeOutQuad"
							data-endspeed="600">
							<span class="sombras_baner_home">
								Los revestimientos de pared están disponibles en una amplia variedad de formatos, <br>
								diseños , colores y texturas. Otorgan un efecto único.
							</span>
						</div>

						<!-- LAYER NR. 4 -->
						<div class="tp-caption sfb fadeout text-center small_white"
							data-x="center"
							data-y="250"
							data-speed="500"
							data-start="1600"
							data-easing="easeOutQuad"
							data-endspeed="600"><a href="revestimientos-libre-mantenimiento.php" class="btn radius-50 btn-dark btn-animated">Ver más<i class="fa fa-arrow-right"></i></a> <span class="pl-5 pr-5">o</span> <a href="contacto.php" class="btn radius-50 btn-default btn-animated">Contáctenos <i class="fa fa-envelope"></i></a>
						</div>

					</li>
					<!-- slide 5 end -->

				</ul>
				<div class="tp-bannertimer"></div>
			</div>
		</div>
		<!-- slider revolution end -->

	</div>
	<!-- slideshow end -->

</div>
<!-- Slide Home end -->