<!-- Carrousel trabajos realizados -->
<!-- ================ -->
<section class="pv-30 light-gray-bg padding-bottom-clear">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<h2 class="text-center">PORTFOLIO</h2>
				<div class="separator"></div>
			</div>
		</div>
	</div>
	<div class="space-bottom">
		<div class="owl-carousel carousel">
			<div class="image-box shadow text-center">
				<div class="overlay-container">
					<img src="images/trabajos/trabajo-1/deck-ecologico-1.jpg" alt="deck sintecticos en PVC 1">
					<div class="overlay-top">
						<div class="text">
							<h3><a href="deck-ecologico-color-roble-montana.php">Deck Ecologico <br>Roble Montaña</a></h3>
						</div>
					</div>
					<div class="overlay-bottom">
						<div class="links">
							<a href="deck-ecologico-color-roble.php" class="btn btn-gray-transparent btn-animated">Ver detalles<i class="pl-10 fa fa-arrow-right"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="image-box shadow text-center">
				<div class="overlay-container">
					<img src="images/trabajos/trabajo-2/deck-ecologico-2.jpg" alt="deck sintecticos en PVC 2">
					<div class="overlay-top">
						<div class="text">
							<h3><a href="deck-ecologico-color-gris-nevado.php">Deck Ecologico <br>Gris Nevado</a></h3>
						</div>
					</div>
					<div class="overlay-bottom">
						<div class="links">
							<a href="deck-ecologico-color-gris-nevado.php" class="btn btn-gray-transparent btn-animated">Ver detalles<i class="pl-10 fa fa-arrow-right"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="image-box shadow text-center">
				<div class="overlay-container">
					<img src="images/trabajos/trabajo-3/deck-ecologico-3.jpg" alt="deck sintecticos en PVC 3">
					<div class="overlay-top">
						<div class="text">
							<h3><a href="deck-ecologico-color-castano-country.php">Deck Ecologico <br>Color Castaño</a></h3>
						</div>
					</div>
					<div class="overlay-bottom">
						<div class="links">
							<a href="deck-ecologico-color-castano-country.php" class="btn btn-gray-transparent btn-animated">Ver detalles<i class="pl-10 fa fa-arrow-right"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="image-box shadow text-center">
				<div class="overlay-container">
					<img src="images/trabajos/trabajo-4/deck-ecologico-4.jpg" alt="deck sintecticos en PVC 4">
					<div class="overlay-top">
						<div class="text">
							<h3><a href="deck-ecologico-color-lapacho.php">Deck Ecologico <br>Color Lapacho</a></h3>
						</div>
					</div>
					<div class="overlay-bottom">
						<div class="links">
							<a href="deck-ecologico-color-lapacho.php" class="btn btn-gray-transparent btn-animated">Ver detalles<i class="pl-10 fa fa-arrow-right"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Carrousel trabajos realizados end -->

